# -*- mode: ruby -*-
# vi: set ft=ruby :

$master_script = <<SCRIPT
#!/bin/bash
apt-get install curl -y
apt-get install screen -y
apt-get install wget -y

add-apt-repository -y ppa:webupd8team/java
wget http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
echo 'deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' | sudo tee /etc/apt/sources.list.d/elasticsearch.list
echo 'deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' | sudo tee /etc/apt/sources.list.d/logstash.list

apt-get update
#apt-get -q -y --force-yes install oracle-java8-installer
#apt-get install collectd -y
#apt-get install collectd-utils -y
#apt-get -y install elasticsearch=1.4.4
#apt-get -y install logstash

cd

wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
tar xvf kibana-4.0.1-linux-x64.tar.gz
mkdir -p /opt/kibana
cp -R ~/kibana-4.0.1-linux-x64/* /opt/kibana/
cd /etc/init.d && sudo wget https://gist.githubusercontent.com/thisismitch/8b15ac909aed214ad04a/raw/bce61d85643c2dcdfbc2728c55a41dab444dca20/kibana4
chmod +x /etc/init.d/kibana4
update-rc.d kibana4 defaults 96 9
#service kibana4 start
#service elasticsearch start
#service logstash start
#service collectd start

SCRIPT

$hosts_script = <<SCRIPT
cat > /etc/hosts <<EOF
127.0.0.1       localhost
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
SCRIPT



Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

# Manage /etc/hosts on host and VMs
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

config.vm.define :monit do |monit|
    monit.vm.provider :virtualbox do |v|
      v.name = "vm-cluster-monit"
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end
    monit.vm.network :private_network, ip: "10.211.55.100"
    monit.vm.hostname = "monit"
    monit.vm.provision :shell, :inline => $hosts_script
    monit.vm.provision :hostmanager
    monit.vm.provision :shell, :inline => $master_script
  end
end